require(mappoly)
load("~/Documents/EiB_May_2019/Demos/mapping/potato/temp.RData")
genoprob.ls<-list(lg1 = genoprob.lg12, lg2 = genoprob.lg12)
saveRDS(genoprob.ls, file = "~/Documents/EiB_May_2019/Demos/mapping/potato/genoprob_list.rds")
new.name<-readRDS("~/Documents/EiB_May_2019/Demos/mapping/potato/genoprob_list.rds")
final.map<-list(lg1=lg12.map.prior$reestimated.map, lg2= lg12.map.prior$reestimated.map)
saveRDS(final.map, file = "~/Documents/EiB_May_2019/Demos/mapping/potato/final.map.rds")
saveRDS(dat.pot.filt, file = "~/Documents/EiB_May_2019/Demos/mapping/potato/input.data.rds")
identical(new.name, genoprob.ls)
